name: CI/CD Pipeline with Direct Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-database-connection-API:
    runs-on: ubuntu-latest
    name: Database and API Testing Unit 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

     # - name: Set up environment variables
     #   run: |
     #     echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
     #     echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
     #     echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
     #     echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
     #     echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV

      #- name: Run FastAPI Tests
       # run: pytest tests/test.py

  build-and-test:
    runs-on: ubuntu-latest
    name: Frontend and Backend Testing Unit 
    needs: test-database-connection-API
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Start services
        run: |
          nohup chroma run --path chromadb --host 0.0.0.0 --port 8000 > chroma.log 2>&1 &
          nohup uvicorn backend:app --host 0.0.0.0 --port 5000 --reload > uvicorn.log 2>&1 &
          nohup streamlit run chatbot.py --server.port=8051 --server.headless true > streamlit.log 2>&1 &

      - name: Check if services are running
        run: |
          sleep 10
          ss -tulnp | grep -E '8000|5000|8051'

  revert-on-failure:
    runs-on: ubuntu-latest
    if: failure()
    needs: 
      - test-database-connection-API
      - build-and-test
    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full commit history

      - name: Revert Last Commit
        run: |
          git reset --hard HEAD~1
          git push --force "https://${{ secrets.GH_PAT }}@github.com/mfldosari/WeCloudData-ChatBot.git" main

